version: '3'
services:

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  pgen:
    image: helpdev/pgen
    environment:
      PROTOCOL_DECIMAL_PLACES_AFTER_DATE: 8
      REDIS_ADDRESS: "redis:6379"
    depends_on:
      - redis
    ports:
      - "5000:5000"
