version: '3'
services:

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  pgen:
    image: helpdev/pgen
    environment:
      PROTOCOL_DECIMAL_PLACES_AFTER_DATE: 8
      REDIS_ADDRESS: "redis:6379"
    depends_on:
      - redis
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus:v2.25.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    ports:
      - "9090:9090"
